name: Deploy Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Yandex Cloud
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          folder-id: ${{ secrets.FOLDER_ID }}
          function-name: 'test'
          runtime: 'python312'
          memory: '128Mb'
          entrypoint: 'index.handler'
          environment: |
            DEBUG=True
            COUNT=1
          include: |
            *.py
            requirements.txt
